# Generated by Django 4.2.26 on 2025-11-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="search_keywords",
            field=models.TextField(
                blank=True,
                help_text="Palavras-chave separadas por vírgula para sugestões de busca",
                null=True,
            ),
        ),
    ]
