# Generated by Django 4.2.26 on 2025-11-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_servicecategory_search_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicecategory",
            name="icon_url",
            field=models.URLField(
                blank=True,
                help_text="URL externa (opcional). Se vazio, usa ícone SVG local.",
                max_length=500,
                null=True,
            ),
        ),
    ]
