# Generated by Django 5.1.1 on 2025-11-27 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('locations', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='professional',
            name='service_cities',
            field=models.ManyToManyField(blank=True, related_name='professionals', to='locations.city'),
        ),
        migrations.AddField(
            model_name='professional',
            name='service_neighborhoods',
            field=models.ManyToManyField(blank=True, related_name='professionals', to='locations.neighborhood'),
        ),
        migrations.AddField(
            model_name='professional',
            name='service_provinces',
            field=models.ManyToManyField(related_name='professionals', to='locations.province'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='accounts.professional'),
        ),
    ]
