# Generated by Django 5.1.1 on 2025-11-28 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_professional_contact_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views', to='accounts.professional')),
            ],
            options={
                'verbose_name': 'Visualização de Perfil',
                'verbose_name_plural': 'Visualizações de Perfil',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['professional', '-created_at'], name='accounts_pr_profess_eb6cee_idx')],
            },
        ),
    ]
