# Generated by Django 5.1.1 on 2025-11-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profileview'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última vez online'),
        ),
    ]
