# Generated by Django 5.1.1 on 2025-11-28 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_professional_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Conta Bloqueada'),
        ),
        migrations.AddField(
            model_name='client',
            name='report_count',
            field=models.IntegerField(default=0, verbose_name='Número de Denúncias'),
        ),
        migrations.AddField(
            model_name='professional',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Conta Bloqueada'),
        ),
        migrations.AddField(
            model_name='professional',
            name='report_count',
            field=models.IntegerField(default=0, verbose_name='Número de Denúncias'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fake_profile', 'Perfil Falso ou Suspeito'), ('inappropriate_content', 'Conteúdo Inadequado'), ('spam', 'Spam ou Comportamento Abusivo'), ('scam', 'Golpe ou Fraude'), ('harassment', 'Assédio ou Bullying'), ('poor_service', 'Serviço de Baixa Qualidade'), ('no_show', 'Não Compareceu ao Serviço'), ('other', 'Outro')], max_length=50, verbose_name='Motivo')),
                ('description', models.TextField(help_text='Descreva o problema em detalhes', verbose_name='Descrição')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('reviewing', 'Em Análise'), ('resolved', 'Resolvido'), ('dismissed', 'Descartado')], default='pending', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Notas do Administrador')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='accounts.client')),
                ('reported_professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='accounts.professional')),
                ('reporter_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to='accounts.client')),
                ('reporter_professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to='accounts.professional')),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='accounts_re_status_02566d_idx'), models.Index(fields=['reported_professional', '-created_at'], name='accounts_re_reporte_8965ff_idx'), models.Index(fields=['reported_client', '-created_at'], name='accounts_re_reporte_5657cd_idx')],
            },
        ),
    ]
